spring.thymeleaf.cache: false
spring.thymeleaf.mode: LEGACYHTML5

# Spring properties
spring:
  application:
     name: entities-controllers

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 5555   # HTTP (Tomcat) port


spring.datasource.url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useSSL=false
spring.datasource.username: root
spring.datasource.password: root
spring.datasource.driver-class-name: com.mysql.jdbc.Driver

spring.jpa.properties.hibernate.show_sql: true
spring.jpa.properties.hibernate.use_sql_comments: true
spring.jpa.properties.hibernate.format_sql: true
