# Spring properties
spring:
  application:
     name: amqp-sender

server:
    port: 0

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/



