spring:
  application:
     name: amqp-receiver

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 7777   # HTTP (Tomcat) port
